### PR TITLE
Update to giter8 version 0.11.0-M1

### PR DESCRIPTION
**Pull request by wolfendale**
Implements #6, #7 and bumps giter8 version to 0.11.0-M1 for dynamic version launching.

### CODE REVIEW

**Comment by eed3si9n** [comment]
Giter8 app is missing 2.12 artifacts. I am publishing them now..

**Comment by wolfendale** [comment]
Closing to reset build now that 2.12 artefacts are published for giter8

**Comment by VEINHORN** [comment]
@eed3si9n @wolfendale hi guys. Does SBT 1.1.0 `new` support conditionals in templates which were added in Giter8 0.10.0?

**Comment by chrisbenincasa** [comment]
Any ETA on this?

**Comment by eed3si9n** [comment]
The Giter8 situation got a bit messy, but I need to get back into it at some point.

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/sbt/sbt-giter8-resolver/pull/16

**Pull request closed without merging**
