### PR TITLE
giter8-launcher 0.12.0

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref https://github.com/foundweekends/giter8/pull/444

### CODE REVIEW

**Comment by xuwei-k** [comment]
When will new version be released? :eyes:

**Comment by eed3si9n** [comment]
Next 1.3.x whenever I release it. It could be this week or next - https://github.com/sbt/sbt/pull/5537

**Comment by eed3si9n** [comment]
Resolver was published to Maven Central immediately - https://repo1.maven.org/maven2/org/scala-sbt/sbt-giter8-resolver/sbt-giter8-resolver_2.12/0.12.0/

**Comment by xuwei-k** [comment]
I see.
BTW missing v0.12.0 tag on github 🙏 
https://github.com/sbt/sbt-giter8-resolver/releases

**Comment by eed3si9n** [comment]
done https://github.com/sbt/sbt-giter8-resolver/releases/tag/v0.12.0

**Pull request merged**
