### PR TITLE
Updated giter8 plugin to 0.8.0

### PR DESCRIPTION
**Pull request by mboogerd**
Ran into an issue where the resolver was not using the latest version of the giter8 plugin (due to maven properties with Stable property). This fixes that issue.

### CODE REVIEW

**Comment by mboogerd** [comment]
After having given this some more thoughts, this is not really a future-proof solution. Would it be possible to exclude this dependency entirely, and instead invoke the giter8 plugin linked with the template itself? This would improve stability for templates relying on different versions (both older and newer) of the plugin, but does require a stable interface to invoke it. Curious after your thoughts about this

**Comment by ravwojdyla** [comment]
+1 want to use the subdirectory feature of `0.8.0`.

**Comment by wsargent** [comment]
+1

**Comment by eed3si9n** [comment]
The problem is that 0.8.0 has too many open issues, i don't want to spread it.

**Comment by ravwojdyla** [comment]
@eed3si9n any chance to get `0.8.0`/`0.9.0` in?

**Comment by eed3si9n** [comment]
I probably first need to release another version of Giter8 that now has conditionals.

**Comment by eed3si9n** [comment]
As @mboogerd wrote, "after having given this some more thoughts, this is not really a future-proof solution."

Now we have a new support for conditionals, which is great. But we also have a bunch of sbt users with no support for it. It's essentially a never ending cat-and-mouse. The solution as he proposed is let the template authors declare the Giter8 version.

I've created https://github.com/sbt/sbt-giter8-resolver/issues/11

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/sbt/sbt-giter8-resolver/pull/16

**Pull request closed without merging**
